In [124]:
import pandas_datareader.data as web
import matplotlib.pyplot as plt
import yfinance as yf
import mplfinance as mpf
from mplfinance.original_flavor import candlestick2_ohlc

yf.pdr_override()

gs = web.get_data_yahoo("078930.KS", start="2023-01-01", end="2024-03-15")

[*********************100%%**********************]  1 of 1 completed

In [ ]:
plt.plot(gs["Adj Close"])

In [ ]:
mpf.plot(gs, type="candle", volume=True, style="charles", mav=(10, 20, 40, 60, 100))

In [120]:
ma5 = gs["Adj Close"].rolling(window=5).mean()
ma10 = gs["Adj Close"].rolling(window=10).mean()
ma20 = gs["Adj Close"].rolling(window=20).mean()
ma60 = gs["Adj Close"].rolling(window=60).mean()
ma120 = gs["Adj Close"].rolling(window=120).mean()

gs.insert(len(gs.columns), "MA5", ma5)
gs.insert(len(gs.columns), "MA10", ma10)
gs.insert(len(gs.columns), "MA20", ma20)
gs.insert(len(gs.columns), "MA60", ma60)
gs.insert(len(gs.columns), "MA120", ma120)

gs.tail(10)

,Open,High,Low,Close,Adj Close,Volume,MA5,MA10,MA20,MA60,MA120
Date,,,,,,,,,,,
2024-02-29,47750.0,49000.0,47350.0,48050.0,48050.0,312266,47510.0,48485.0,49085.0,43279.982682,40725.536686
2024-03-04,49000.0,50300.0,48450.0,49050.0,49050.0,206333,47530.0,48520.0,49222.5,43455.819922,40836.203743
2024-03-05,48600.0,50600.0,48500.0,49100.0,49100.0,146714,47940.0,48280.0,49192.5,43615.233073,40931.991113
2024-03-06,49650.0,49700.0,48600.0,48750.0,48750.0,86356,48540.0,48165.0,49115.0,43773.519466,41033.098307
2024-03-07,49250.0,49450.0,48450.0,48850.0,48850.0,99649,48760.0,48185.0,49080.0,43930.334766,41131.116699
2024-03-08,49350.0,49450.0,48200.0,48700.0,48700.0,120545,48890.0,48200.0,49067.5,44084.650065,41230.238379
2024-03-11,48250.0,48900.0,47800.0,48050.0,48050.0,94007,48690.0,48110.0,48860.0,44227.347591,41319.236816
2024-03-12,48700.0,48700.0,46850.0,46850.0,46850.0,121597,48240.0,48090.0,48602.5,44345.338607,41395.489746
2024-03-13,47300.0,47300.0,46600.0,46850.0,46850.0,86001,47860.0,48200.0,48395.0,44468.820573,41476.057031
2024-03-14,47350.0,50300.0,47000.0,49750.0,49750.0,311063,48040.0,48400.0,48392.5,44633.576042,41575.299967